// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5433.BlindingLight_Sheila.subsystems;

import org.usfirst.frc5433.BlindingLight_Sheila.RobotMap;
import org.usfirst.frc5433.BlindingLight_Sheila.commands.*;
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CounterBase.EncodingType; import edu.wpi.first.wpilibj.PIDSource.PIDSourceParameter;

import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Drive_System extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    Encoder encoder_Front_Left = RobotMap.drive_SystemEncoder_Front_Left;
    Encoder encoder_Front_Right = RobotMap.drive_SystemEncoder_Front_Right;
    Encoder encoder_Rear_Left = RobotMap.drive_SystemEncoder_Rear_Left;
    Encoder encoder_Rear_Right = RobotMap.drive_SystemEncoder_Rear_Right;
    SpeedController drive_Front_Left = RobotMap.drive_SystemDrive_Front_Left;
    SpeedController drive_Front_Right = RobotMap.drive_SystemDrive_Front_Right;
    SpeedController drive_Rear_Left = RobotMap.drive_SystemDrive_Rear_Left;
    SpeedController drive_Rear_Right = RobotMap.drive_SystemDrive_Rear_Right;
    RobotDrive robotDrive41 = RobotMap.drive_SystemRobotDrive41;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

